name: Testar user_data.sh

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-user-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Tornar o script executável
        run: chmod +x project-1-iac/modules/compute/user_data.sh

      - name: Executar o script com debug
        run: project-1-iac/modules/compute/user_data.sh


